### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method parse on channel com.julienvignali/phone_number)

### ISSUE THREAD

**Issue by myamolane** [nashfive/phone_number#19]
run example on ios emulator
flutter version: 1.9.1
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method parse on channel com.julienvignali/phone_number)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      PhoneNumber.parse (package:phone_number/src/phone_number.dart:20:21)
#2      _MyAppState.initPlatformState (package:phone_number_example/main.dart:29:36)
<asynchronous suspension>
#3      _MyAppState.initState (package:phone_number_example/main.dart:21:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4067:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3921:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3103:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2906:12)
#8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1002:16)
#9      RenderObjectToWidgetElement.m<…>

**Comment by Faiyyaz** [comment]
I am getting error on my physical android device

**Comment by nashfive** [comment]
Hi @myamolane,
Sorry I was busy. I've seen that you closed the issue. Let me know if you run into any more issue.

**Comment by Faiyyaz** [comment]
> I am getting error on my physical android device

This was a weird issue. I was getting it due to Facebook plugin when I setup it properly the error went away

**Comment by nashfive** [comment]
@Faiyyaz, yes those kind of errors are weird since it's not easy to figure out which plugin is really causing the issue.

**Comment by hilalbaig** [comment]
This issue is caused due to when you just add plugin and then get dependencies and just hot reload OR hot restart your flutter app. Hot restart or hot reload is not enough to trigger injection of plugin dependencies. You just have to close Or stop your app and then execute flutter run. That’s it. This will solve your issue.

**Comment by garrettlove8** [comment]
I'm experiencing this error when running a test... Has anyone encountered this?

**Comment by Coder-Manuel** [comment]
@garrettlove8 Yes experiencing the same issue when running tests......
Is there a fix @nashfive ?

**Comment by arc-arnob** [comment]
Still getting the same issue while running the test, @Coder-Manuel did you find any fix?

**Comment by arc-arnob** [comment]
@Coder-Manuel I found an alternative phone_numbers_parser, works pretty much the same and passed tests

**Comment by Coder-Manuel** [comment]
Thanks @arc-arnob 
Lemme try it out...
