### ISSUE TITLE
Failing to parse legitimate numbers on IOS with

### ISSUE THREAD

**Issue by passsionforprogramming** [nashfive/phone_number#23]
It works fine on Android, but it is failing to parse legitimate strings when testing on iOS

**Comment by nashfive** [comment]
Can you provide a string that can't be parsed ?

**Comment by passsionforprogramming** [comment]
Actually it works fine now if I take away the country. It doesn't work with the country.

**Comment by nashfive** [comment]
Work on my side...
Can you provide a number with the country code ?
