### ISSUE TITLE
Please provide a simple functioning example app. 

### ISSUE THREAD

**Issue by AlraziBashir** [nashfive/phone_number#29]
I have taken a look at your app and have struggled to create a functioning US phone number E.164 textinputt formater. Please provide a sample working app to help. Thanks

**Comment by nashfive** [comment]
Hi @AlraziBashir 
Currently the plugin doesn't provide anything for TextInputFormatter. It only offers 2 methods to parse or format a string according to a country code. I might add some "as you type" formatting in the future...
