### ISSUE TITLE
ld: warning: Could not find auto-linked library 'swiftFoundation' when including 0.6.2+4 in new empty flutter project

### ISSUE THREAD

**Issue by jasonmurray33** [nashfive/phone_number#30]
Hitting this in a new empty flutter project when including the latest package:
- ld: symbol(s) not found for architecture x86_64
steps: 
* new flutter project
* flutter run - runs successfully on simulator for iPhone 11 Pro (13.6)
* include 0.6.2+4 in pubspec.yaml
* flutter run - same target simulator results in ld: symbol(s) not found for architecture x86_64

Here is the flutter doctor output, is there anything else I'm missing in the config possibly? Thanks!

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.40.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by jasonmurray33** [comment]
I was searching for solutions based on the end of the error output, but the beginning of the error was this: 

ld: warning: Could not find auto-linked library 'swiftFoundation'

Which was resolved by adding  a single empty Swift file to the project and choosing to Create Bridging Header ,as mentioned here https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios

No issues after that.

**Comment by nashfive** [comment]
Hi @jasonmurray33,
I think it is mostly due to the fact that your Flutter project had been created with the Objective-C language rather than Swift, and since the plugin is written in Swift, it causes this link error...
