### ISSUE TITLE
deprecated API

### ISSUE THREAD

**Issue by dgaedcke** [nashfive/phone_number#36]
/phone_number-0.8.1/android/src/main/java/com/julienvignali/phone_number/PhoneNumberPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by jordantsap** [comment]
flutter channel?

**Comment by dgaedcke** [comment]
sorry ... I must have missed your earlier response!!
I've been on the beta channel since that report
but have not seen this in several months ...
