### ISSUE TITLE
Null safety support 

### ISSUE THREAD

**Issue by jaumard** [nashfive/phone_number#40]
Hello :) 

In order to migrate to flutter v2, we need this package to support null safety :) :D 

Anything planed ?

**Comment by nashfive** [comment]
Hi @jaumard! 
It's been done in the latest version : 0.9 

Let me know if it works on your end.
Cheers mate :)

**Comment by jaumard** [comment]
Ha ha too fast for me :D still have 10 package to migrate to null safety but will do when I got here lol 
Thanks a lot!!
