### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by lesiaki** [nashfive/phone_number#5]
Error running pod install
Error launching application on iPhone Xʀ.

**Comment by nashfive** [comment]
Can you provide a bit more information about your setup? Like posting your `flutter doctor -v` and the error you're seeing ?

**Comment by jmcfet** [comment]
I get the following error trying to use the plugin

Xcode build done.                                           14.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET firebase_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/jmcfet/AndroidStudioProjects/firebase-login-flutter-master/ios/Pods/PhoneNumberKit/PhoneNumberKit/Formatter.swift:116:5: warning: 'public' modifier is redundant for instance method declared in a public extension
        public func adjustedNationalNumber() -> String {
        ^~~~~~~

    === BUILD TARGET firebase_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/jmcfet/AndroidStudioProjects/firebase-login-flutter-master/ios/Pods/PhoneNumberKit/PhoneNumberKit/PhoneNumber.swift:69:5: warning: 'public' modifier is redundant for initializer declared in a public extension
        public init(rawNumber: String) throws {
        ^~~~~~~

    /Users/jmcfet/AndroidStudioProjects/firebase-login-flutter-master/ios/Pods/PhoneNumberKit/PhoneNumberKit/PhoneNumber.swift:81:5: warning: 'public' modifier is redundant for initializer declared in a public extension
        public init(rawNumber: String, region: String) throws {
        ^~~~~~~

    /Users/jmcfet/AndroidStudioProjects/firebase-login-flutter-master/ios/Pods/PhoneNumberKit/PhoneNumberKit/PhoneNumber.swift:44:16: warning: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'PhoneNumber' to 'Hashable' by implementing 'hash(into:)' instead
        public var hashValue: Int {
                   ^
    /Users/jmcfet/AndroidStudioProjects/firebase-login-flutter-master/ios/Pods/PhoneNumberKit/PhoneNumberKit/Formatter.swift:116:5: warning: 'public' modifier is redundant for instance method declared in a public extension
        public func adjustedNationalNumber() -> String {
        ^~~~~~~
