### ISSUE TITLE
Is there anyway to force disable RTL in this plugin?

### ISSUE THREAD

**Issue by technosoftkpk** [nashfive/phone_number#58]
Hi there, I am trying to implement this into my app but when tried to change my Local language to Arabic the text box direction is changed to RTL. Is there any workaround so I can force disable RTL mode of the textbox?

**Comment by nashfive** [comment]
Hi @technosoftkpk, 
This has nothing to do with this plugin, as _Text directionality_ is natively supported by Flutter.
Try to enforce it by setting `textDirection` to `TextDirection.ltr` : 
```dart
TextField(..., textDirection: TextDirection.ltr)
```
or by wrapping it in a `Directionality`: 
```Dart
Directionality(
  textDirection: TextDirection.ltr,
  child: TextField()
)
```
